name: build and push docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/worker.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bin3377/firecrawl-worker:latest
    
      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          file: ./apps/api/server.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bin3377/firecrawl-server:latest
